// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.AttemptDataOnDemand;
import cn.jhc.myexam.server.domain.AttemptIntegrationTest;
import cn.jhc.myexam.server.repository.AttemptRepository;
import cn.jhc.myexam.server.service.AttemptService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AttemptIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttemptIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttemptIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AttemptIntegrationTest: @Transactional;
    
    @Autowired
    AttemptDataOnDemand AttemptIntegrationTest.dod;
    
    @Autowired
    AttemptService AttemptIntegrationTest.attemptService;
    
    @Autowired
    AttemptRepository AttemptIntegrationTest.attemptRepository;
    
    @Test
    public void AttemptIntegrationTest.testCountAllAttempts() {
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", dod.getRandomAttempt());
        long count = attemptService.countAllAttempts();
        Assert.assertTrue("Counter for 'Attempt' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttemptIntegrationTest.testFindAttempt() {
        Attempt obj = dod.getRandomAttempt();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to provide an identifier", id);
        obj = attemptService.findAttempt(id);
        Assert.assertNotNull("Find method for 'Attempt' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Attempt' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AttemptIntegrationTest.testFindAllAttempts() {
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", dod.getRandomAttempt());
        long count = attemptService.countAllAttempts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Attempt', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Attempt> result = attemptService.findAllAttempts();
        Assert.assertNotNull("Find all method for 'Attempt' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Attempt' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttemptIntegrationTest.testFindAttemptEntries() {
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", dod.getRandomAttempt());
        long count = attemptService.countAllAttempts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Attempt> result = attemptService.findAttemptEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Attempt' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Attempt' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttemptIntegrationTest.testFlush() {
        Attempt obj = dod.getRandomAttempt();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to provide an identifier", id);
        obj = attemptService.findAttempt(id);
        Assert.assertNotNull("Find method for 'Attempt' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAttempt(obj);
        Integer currentVersion = obj.getVersion();
        attemptRepository.flush();
        Assert.assertTrue("Version for 'Attempt' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttemptIntegrationTest.testUpdateAttemptUpdate() {
        Attempt obj = dod.getRandomAttempt();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to provide an identifier", id);
        obj = attemptService.findAttempt(id);
        boolean modified =  dod.modifyAttempt(obj);
        Integer currentVersion = obj.getVersion();
        Attempt merged = attemptService.updateAttempt(obj);
        attemptRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Attempt' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttemptIntegrationTest.testSaveAttempt() {
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", dod.getRandomAttempt());
        Attempt obj = dod.getNewTransientAttempt(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Attempt' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Attempt' identifier to be null", obj.getId());
        try {
            attemptService.saveAttempt(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        attemptRepository.flush();
        Assert.assertNotNull("Expected 'Attempt' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AttemptIntegrationTest.testDeleteAttempt() {
        Attempt obj = dod.getRandomAttempt();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attempt' failed to provide an identifier", id);
        obj = attemptService.findAttempt(id);
        attemptService.deleteAttempt(obj);
        attemptRepository.flush();
        Assert.assertNull("Failed to remove 'Attempt' with identifier '" + id + "'", attemptService.findAttempt(id));
    }
    
}
