// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.BriefAnswerDataOnDemand;
import cn.jhc.myexam.server.domain.BriefAnswerIntegrationTest;
import cn.jhc.myexam.server.repository.BriefAnswerRepository;
import cn.jhc.myexam.server.service.BriefAnswerService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BriefAnswerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BriefAnswerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BriefAnswerIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BriefAnswerIntegrationTest: @Transactional;
    
    @Autowired
    BriefAnswerDataOnDemand BriefAnswerIntegrationTest.dod;
    
    @Autowired
    BriefAnswerService BriefAnswerIntegrationTest.briefAnswerService;
    
    @Autowired
    BriefAnswerRepository BriefAnswerIntegrationTest.briefAnswerRepository;
    
    @Test
    public void BriefAnswerIntegrationTest.testCountAllBriefAnswers() {
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", dod.getRandomBriefAnswer());
        long count = briefAnswerService.countAllBriefAnswers();
        Assert.assertTrue("Counter for 'BriefAnswer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testFindBriefAnswer() {
        BriefAnswer obj = dod.getRandomBriefAnswer();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to provide an identifier", id);
        obj = briefAnswerService.findBriefAnswer(id);
        Assert.assertNotNull("Find method for 'BriefAnswer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BriefAnswer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testFindAllBriefAnswers() {
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", dod.getRandomBriefAnswer());
        long count = briefAnswerService.countAllBriefAnswers();
        Assert.assertTrue("Too expensive to perform a find all test for 'BriefAnswer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BriefAnswer> result = briefAnswerService.findAllBriefAnswers();
        Assert.assertNotNull("Find all method for 'BriefAnswer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BriefAnswer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testFindBriefAnswerEntries() {
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", dod.getRandomBriefAnswer());
        long count = briefAnswerService.countAllBriefAnswers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BriefAnswer> result = briefAnswerService.findBriefAnswerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BriefAnswer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BriefAnswer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testFlush() {
        BriefAnswer obj = dod.getRandomBriefAnswer();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to provide an identifier", id);
        obj = briefAnswerService.findBriefAnswer(id);
        Assert.assertNotNull("Find method for 'BriefAnswer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBriefAnswer(obj);
        Integer currentVersion = obj.getVersion();
        briefAnswerRepository.flush();
        Assert.assertTrue("Version for 'BriefAnswer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testUpdateBriefAnswerUpdate() {
        BriefAnswer obj = dod.getRandomBriefAnswer();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to provide an identifier", id);
        obj = briefAnswerService.findBriefAnswer(id);
        boolean modified =  dod.modifyBriefAnswer(obj);
        Integer currentVersion = obj.getVersion();
        BriefAnswer merged = briefAnswerService.updateBriefAnswer(obj);
        briefAnswerRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BriefAnswer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testSaveBriefAnswer() {
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", dod.getRandomBriefAnswer());
        BriefAnswer obj = dod.getNewTransientBriefAnswer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BriefAnswer' identifier to be null", obj.getId());
        try {
            briefAnswerService.saveBriefAnswer(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        briefAnswerRepository.flush();
        Assert.assertNotNull("Expected 'BriefAnswer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BriefAnswerIntegrationTest.testDeleteBriefAnswer() {
        BriefAnswer obj = dod.getRandomBriefAnswer();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BriefAnswer' failed to provide an identifier", id);
        obj = briefAnswerService.findBriefAnswer(id);
        briefAnswerService.deleteBriefAnswer(obj);
        briefAnswerRepository.flush();
        Assert.assertNull("Failed to remove 'BriefAnswer' with identifier '" + id + "'", briefAnswerService.findBriefAnswer(id));
    }
    
}
