// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.CapabilityDataOnDemand;
import cn.jhc.myexam.server.domain.CapabilityIntegrationTest;
import cn.jhc.myexam.server.repository.CapabilityRepository;
import cn.jhc.myexam.server.service.CapabilityService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CapabilityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CapabilityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CapabilityIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CapabilityIntegrationTest: @Transactional;
    
    @Autowired
    CapabilityDataOnDemand CapabilityIntegrationTest.dod;
    
    @Autowired
    CapabilityService CapabilityIntegrationTest.capabilityService;
    
    @Autowired
    CapabilityRepository CapabilityIntegrationTest.capabilityRepository;
    
    @Test
    public void CapabilityIntegrationTest.testCountAllCapabilitys() {
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", dod.getRandomCapability());
        long count = capabilityService.countAllCapabilitys();
        Assert.assertTrue("Counter for 'Capability' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CapabilityIntegrationTest.testFindCapability() {
        Capability obj = dod.getRandomCapability();
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capability' failed to provide an identifier", id);
        obj = capabilityService.findCapability(id);
        Assert.assertNotNull("Find method for 'Capability' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Capability' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CapabilityIntegrationTest.testFindAllCapabilitys() {
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", dod.getRandomCapability());
        long count = capabilityService.countAllCapabilitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Capability', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Capability> result = capabilityService.findAllCapabilitys();
        Assert.assertNotNull("Find all method for 'Capability' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Capability' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CapabilityIntegrationTest.testFindCapabilityEntries() {
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", dod.getRandomCapability());
        long count = capabilityService.countAllCapabilitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Capability> result = capabilityService.findCapabilityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Capability' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Capability' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CapabilityIntegrationTest.testFlush() {
        Capability obj = dod.getRandomCapability();
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capability' failed to provide an identifier", id);
        obj = capabilityService.findCapability(id);
        Assert.assertNotNull("Find method for 'Capability' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCapability(obj);
        Integer currentVersion = obj.getVersion();
        capabilityRepository.flush();
        Assert.assertTrue("Version for 'Capability' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapabilityIntegrationTest.testUpdateCapabilityUpdate() {
        Capability obj = dod.getRandomCapability();
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capability' failed to provide an identifier", id);
        obj = capabilityService.findCapability(id);
        boolean modified =  dod.modifyCapability(obj);
        Integer currentVersion = obj.getVersion();
        Capability merged = capabilityService.updateCapability(obj);
        capabilityRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Capability' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CapabilityIntegrationTest.testSaveCapability() {
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", dod.getRandomCapability());
        Capability obj = dod.getNewTransientCapability(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Capability' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Capability' identifier to be null", obj.getId());
        try {
            capabilityService.saveCapability(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        capabilityRepository.flush();
        Assert.assertNotNull("Expected 'Capability' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CapabilityIntegrationTest.testDeleteCapability() {
        Capability obj = dod.getRandomCapability();
        Assert.assertNotNull("Data on demand for 'Capability' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Capability' failed to provide an identifier", id);
        obj = capabilityService.findCapability(id);
        capabilityService.deleteCapability(obj);
        capabilityRepository.flush();
        Assert.assertNull("Failed to remove 'Capability' with identifier '" + id + "'", capabilityService.findCapability(id));
    }
    
}
