// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.Capability;
import cn.jhc.myexam.server.domain.CapabilityDataOnDemand;
import cn.jhc.myexam.server.repository.CapabilityRepository;
import cn.jhc.myexam.server.service.CapabilityService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CapabilityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CapabilityDataOnDemand: @Component;
    
    private Random CapabilityDataOnDemand.rnd = new SecureRandom();
    
    private List<Capability> CapabilityDataOnDemand.data;
    
    @Autowired
    CapabilityService CapabilityDataOnDemand.capabilityService;
    
    @Autowired
    CapabilityRepository CapabilityDataOnDemand.capabilityRepository;
    
    public Capability CapabilityDataOnDemand.getNewTransientCapability(int index) {
        Capability obj = new Capability();
        setName(obj, index);
        return obj;
    }
    
    public void CapabilityDataOnDemand.setName(Capability obj, int index) {
        String name = "name_" + index;
        if (name.length() > 128) {
            name = name.substring(0, 128);
        }
        obj.setName(name);
    }
    
    public Capability CapabilityDataOnDemand.getSpecificCapability(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Capability obj = data.get(index);
        Long id = obj.getId();
        return capabilityService.findCapability(id);
    }
    
    public Capability CapabilityDataOnDemand.getRandomCapability() {
        init();
        Capability obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return capabilityService.findCapability(id);
    }
    
    public boolean CapabilityDataOnDemand.modifyCapability(Capability obj) {
        return false;
    }
    
    public void CapabilityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = capabilityService.findCapabilityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Capability' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Capability>();
        for (int i = 0; i < 10; i++) {
            Capability obj = getNewTransientCapability(i);
            try {
                capabilityService.saveCapability(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            capabilityRepository.flush();
            data.add(obj);
        }
    }
    
}
