// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.FillBlankDataOnDemand;
import cn.jhc.myexam.server.domain.FillBlankIntegrationTest;
import cn.jhc.myexam.server.repository.FillBlankRepository;
import cn.jhc.myexam.server.service.FillBlankService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FillBlankIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FillBlankIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FillBlankIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FillBlankIntegrationTest: @Transactional;
    
    @Autowired
    FillBlankDataOnDemand FillBlankIntegrationTest.dod;
    
    @Autowired
    FillBlankService FillBlankIntegrationTest.fillBlankService;
    
    @Autowired
    FillBlankRepository FillBlankIntegrationTest.fillBlankRepository;
    
    @Test
    public void FillBlankIntegrationTest.testCountAllFillBlanks() {
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", dod.getRandomFillBlank());
        long count = fillBlankService.countAllFillBlanks();
        Assert.assertTrue("Counter for 'FILL_BLANK' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FillBlankIntegrationTest.testFindFillBlank() {
        FillBlank obj = dod.getRandomFillBlank();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to provide an identifier", id);
        obj = fillBlankService.findFillBlank(id);
        Assert.assertNotNull("Find method for 'FILL_BLANK' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FILL_BLANK' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FillBlankIntegrationTest.testFindAllFillBlanks() {
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", dod.getRandomFillBlank());
        long count = fillBlankService.countAllFillBlanks();
        Assert.assertTrue("Too expensive to perform a find all test for 'FILL_BLANK', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FillBlank> result = fillBlankService.findAllFillBlanks();
        Assert.assertNotNull("Find all method for 'FILL_BLANK' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FILL_BLANK' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FillBlankIntegrationTest.testFindFillBlankEntries() {
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", dod.getRandomFillBlank());
        long count = fillBlankService.countAllFillBlanks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FillBlank> result = fillBlankService.findFillBlankEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FILL_BLANK' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FILL_BLANK' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FillBlankIntegrationTest.testFlush() {
        FillBlank obj = dod.getRandomFillBlank();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to provide an identifier", id);
        obj = fillBlankService.findFillBlank(id);
        Assert.assertNotNull("Find method for 'FILL_BLANK' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFillBlank(obj);
        Integer currentVersion = obj.getVersion();
        fillBlankRepository.flush();
        Assert.assertTrue("Version for 'FILL_BLANK' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FillBlankIntegrationTest.testUpdateFillBlankUpdate() {
        FillBlank obj = dod.getRandomFillBlank();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to provide an identifier", id);
        obj = fillBlankService.findFillBlank(id);
        boolean modified =  dod.modifyFillBlank(obj);
        Integer currentVersion = obj.getVersion();
        FillBlank merged = fillBlankService.updateFillBlank(obj);
        fillBlankRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FILL_BLANK' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FillBlankIntegrationTest.testSaveFillBlank() {
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", dod.getRandomFillBlank());
        FillBlank obj = dod.getNewTransientFillBlank(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FILL_BLANK' identifier to be null", obj.getId());
        try {
            fillBlankService.saveFillBlank(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        fillBlankRepository.flush();
        Assert.assertNotNull("Expected 'FILL_BLANK' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FillBlankIntegrationTest.testDeleteFillBlank() {
        FillBlank obj = dod.getRandomFillBlank();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FILL_BLANK' failed to provide an identifier", id);
        obj = fillBlankService.findFillBlank(id);
        fillBlankService.deleteFillBlank(obj);
        fillBlankRepository.flush();
        Assert.assertNull("Failed to remove 'FILL_BLANK' with identifier '" + id + "'", fillBlankService.findFillBlank(id));
    }
    
}
