// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.GlossaryDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GlossaryDataOnDemand_Roo_Configurable {
    
    declare @type: GlossaryDataOnDemand: @Configurable;
    
}
