// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.Role;
import cn.jhc.myexam.server.domain.RoleDataOnDemand;
import cn.jhc.myexam.server.repository.RoleRepository;
import cn.jhc.myexam.server.service.RoleService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoleDataOnDemand: @Component;
    
    private Random RoleDataOnDemand.rnd = new SecureRandom();
    
    private List<Role> RoleDataOnDemand.data;
    
    @Autowired
    RoleService RoleDataOnDemand.roleService;
    
    @Autowired
    RoleRepository RoleDataOnDemand.roleRepository;
    
    public Role RoleDataOnDemand.getNewTransientRole(int index) {
        Role obj = new Role();
        setDescription(obj, index);
        setRolename(obj, index);
        return obj;
    }
    
    public void RoleDataOnDemand.setDescription(Role obj, int index) {
        String description = "description_" + index;
        if (description.length() > 2048) {
            description = description.substring(0, 2048);
        }
        obj.setDescription(description);
    }
    
    public void RoleDataOnDemand.setRolename(Role obj, int index) {
        String rolename = "rolename_" + index;
        if (rolename.length() > 64) {
            rolename = rolename.substring(0, 64);
        }
        obj.setRolename(rolename);
    }
    
    public Role RoleDataOnDemand.getSpecificRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Role obj = data.get(index);
        Long id = obj.getId();
        return roleService.findRole(id);
    }
    
    public Role RoleDataOnDemand.getRandomRole() {
        init();
        Role obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return roleService.findRole(id);
    }
    
    public boolean RoleDataOnDemand.modifyRole(Role obj) {
        return false;
    }
    
    public void RoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = roleService.findRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Role' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Role>();
        for (int i = 0; i < 10; i++) {
            Role obj = getNewTransientRole(i);
            try {
                roleService.saveRole(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            roleRepository.flush();
            data.add(obj);
        }
    }
    
}
