// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.jhc.myexam.server.domain;

import cn.jhc.myexam.server.domain.TrueOrFalseDataOnDemand;
import cn.jhc.myexam.server.domain.TrueOrFalseIntegrationTest;
import cn.jhc.myexam.server.repository.TrueOrFalseRepository;
import cn.jhc.myexam.server.service.TrueOrFalseService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TrueOrFalseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TrueOrFalseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TrueOrFalseIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TrueOrFalseIntegrationTest: @Transactional;
    
    @Autowired
    TrueOrFalseDataOnDemand TrueOrFalseIntegrationTest.dod;
    
    @Autowired
    TrueOrFalseService TrueOrFalseIntegrationTest.trueOrFalseService;
    
    @Autowired
    TrueOrFalseRepository TrueOrFalseIntegrationTest.trueOrFalseRepository;
    
    @Test
    public void TrueOrFalseIntegrationTest.testCountAllTrueOrFalses() {
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", dod.getRandomTrueOrFalse());
        long count = trueOrFalseService.countAllTrueOrFalses();
        Assert.assertTrue("Counter for 'TrueOrFalse' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testFindTrueOrFalse() {
        TrueOrFalse obj = dod.getRandomTrueOrFalse();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to provide an identifier", id);
        obj = trueOrFalseService.findTrueOrFalse(id);
        Assert.assertNotNull("Find method for 'TrueOrFalse' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TrueOrFalse' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testFindAllTrueOrFalses() {
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", dod.getRandomTrueOrFalse());
        long count = trueOrFalseService.countAllTrueOrFalses();
        Assert.assertTrue("Too expensive to perform a find all test for 'TrueOrFalse', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TrueOrFalse> result = trueOrFalseService.findAllTrueOrFalses();
        Assert.assertNotNull("Find all method for 'TrueOrFalse' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TrueOrFalse' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testFindTrueOrFalseEntries() {
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", dod.getRandomTrueOrFalse());
        long count = trueOrFalseService.countAllTrueOrFalses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TrueOrFalse> result = trueOrFalseService.findTrueOrFalseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TrueOrFalse' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TrueOrFalse' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testFlush() {
        TrueOrFalse obj = dod.getRandomTrueOrFalse();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to provide an identifier", id);
        obj = trueOrFalseService.findTrueOrFalse(id);
        Assert.assertNotNull("Find method for 'TrueOrFalse' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTrueOrFalse(obj);
        Integer currentVersion = obj.getVersion();
        trueOrFalseRepository.flush();
        Assert.assertTrue("Version for 'TrueOrFalse' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testUpdateTrueOrFalseUpdate() {
        TrueOrFalse obj = dod.getRandomTrueOrFalse();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to provide an identifier", id);
        obj = trueOrFalseService.findTrueOrFalse(id);
        boolean modified =  dod.modifyTrueOrFalse(obj);
        Integer currentVersion = obj.getVersion();
        TrueOrFalse merged = trueOrFalseService.updateTrueOrFalse(obj);
        trueOrFalseRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TrueOrFalse' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testSaveTrueOrFalse() {
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", dod.getRandomTrueOrFalse());
        TrueOrFalse obj = dod.getNewTransientTrueOrFalse(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TrueOrFalse' identifier to be null", obj.getId());
        try {
            trueOrFalseService.saveTrueOrFalse(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        trueOrFalseRepository.flush();
        Assert.assertNotNull("Expected 'TrueOrFalse' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TrueOrFalseIntegrationTest.testDeleteTrueOrFalse() {
        TrueOrFalse obj = dod.getRandomTrueOrFalse();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TrueOrFalse' failed to provide an identifier", id);
        obj = trueOrFalseService.findTrueOrFalse(id);
        trueOrFalseService.deleteTrueOrFalse(obj);
        trueOrFalseRepository.flush();
        Assert.assertNull("Failed to remove 'TrueOrFalse' with identifier '" + id + "'", trueOrFalseService.findTrueOrFalse(id));
    }
    
}
