// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationEntityTypesProcessor;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.AttemptDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.BriefAnswerDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.CategoryDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.FillBlankDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.GlossaryDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.QuizDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.RoleDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.SingleChoiceDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.TrueOrFalseDesktopListView;
import cn.jhc.myexam.client.managed.ui.desktop.UserDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.AttemptMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.BriefAnswerMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.CategoryMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.FillBlankMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.GlossaryMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.QuizMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.RoleMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.SingleChoiceMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.TrueOrFalseMobileListView;
import cn.jhc.myexam.client.managed.ui.mobile.UserMobileListView;
import cn.jhc.myexam.client.proxy.AttemptProxy;
import cn.jhc.myexam.client.proxy.BriefAnswerProxy;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.FillBlankProxy;
import cn.jhc.myexam.client.proxy.GlossaryProxy;
import cn.jhc.myexam.client.proxy.QuizProxy;
import cn.jhc.myexam.client.proxy.RoleProxy;
import cn.jhc.myexam.client.proxy.SingleChoiceProxy;
import cn.jhc.myexam.client.proxy.TrueOrFalseProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyListPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleAttempt(AttemptProxy isNull) {
                setResult(new AttemptListActivity(requests, ScaffoldApp.isMobile() ? AttemptMobileListView.instance() : AttemptDesktopListView.instance(), placeController));
            }

            @Override
            public void handleBriefAnswer(BriefAnswerProxy isNull) {
                setResult(new BriefAnswerListActivity(requests, ScaffoldApp.isMobile() ? BriefAnswerMobileListView.instance() : BriefAnswerDesktopListView.instance(), placeController));
            }

            @Override
            public void handleCategory(CategoryProxy isNull) {
                setResult(new CategoryListActivity(requests, ScaffoldApp.isMobile() ? CategoryMobileListView.instance() : CategoryDesktopListView.instance(), placeController));
            }

            @Override
            public void handleFillBlank(FillBlankProxy isNull) {
                setResult(new FillBlankListActivity(requests, ScaffoldApp.isMobile() ? FillBlankMobileListView.instance() : FillBlankDesktopListView.instance(), placeController));
            }

            @Override
            public void handleGlossary(GlossaryProxy isNull) {
                setResult(new GlossaryListActivity(requests, ScaffoldApp.isMobile() ? GlossaryMobileListView.instance() : GlossaryDesktopListView.instance(), placeController));
            }

            @Override
            public void handleQuiz(QuizProxy isNull) {
                setResult(new QuizListActivity(requests, ScaffoldApp.isMobile() ? QuizMobileListView.instance() : QuizDesktopListView.instance(), placeController));
            }

            @Override
            public void handleRole(RoleProxy isNull) {
                setResult(new RoleListActivity(requests, ScaffoldApp.isMobile() ? RoleMobileListView.instance() : RoleDesktopListView.instance(), placeController));
            }

            @Override
            public void handleSingleChoice(SingleChoiceProxy isNull) {
                setResult(new SingleChoiceListActivity(requests, ScaffoldApp.isMobile() ? SingleChoiceMobileListView.instance() : SingleChoiceDesktopListView.instance(), placeController));
            }

            @Override
            public void handleTrueOrFalse(TrueOrFalseProxy isNull) {
                setResult(new TrueOrFalseListActivity(requests, ScaffoldApp.isMobile() ? TrueOrFalseMobileListView.instance() : TrueOrFalseDesktopListView.instance(), placeController));
            }

            @Override
            public void handleUser(UserProxy isNull) {
                setResult(new UserListActivity(requests, ScaffoldApp.isMobile() ? UserMobileListView.instance() : UserDesktopListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
