// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.AttemptDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.AttemptDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.AttemptDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.AttemptMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.AttemptMobileEditView;
import cn.jhc.myexam.client.proxy.AttemptProxy;
import cn.jhc.myexam.client.proxy.QuizProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.request.AttemptRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import cn.jhc.myexam.shared.domain.QuestionType;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class AttemptActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        AttemptDesktopEditView.instance().setCreating(true);
        Activity activity = new AttemptEditActivity(null, factory, ScaffoldApp.isMobile() ? AttemptMobileEditView.instance() : AttemptDesktopEditView.instance(), placeController);
        return new AttemptEditActivityWrapper(factory, ScaffoldApp.isMobile() ? AttemptMobileEditView.instance() : AttemptDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<AttemptProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<AttemptProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        AttemptDesktopEditView.instance().setCreating(false);
        EntityProxyId<AttemptProxy> proxyId = coerceId(place);
        Activity activity = new AttemptEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? AttemptMobileEditView.instance() : AttemptDesktopEditView.instance(), placeController);
        return new AttemptEditActivityWrapper(factory, ScaffoldApp.isMobile() ? AttemptMobileEditView.instance() : AttemptDesktopEditView.instance(), activity, proxyId);
    }
}
