// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.BriefAnswerDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.BriefAnswerDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.BriefAnswerDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.BriefAnswerMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.BriefAnswerMobileEditView;
import cn.jhc.myexam.client.proxy.BriefAnswerProxy;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.request.BriefAnswerRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class BriefAnswerActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        BriefAnswerDesktopEditView.instance().setCreating(true);
        Activity activity = new BriefAnswerEditActivity(null, factory, ScaffoldApp.isMobile() ? BriefAnswerMobileEditView.instance() : BriefAnswerDesktopEditView.instance(), placeController);
        return new BriefAnswerEditActivityWrapper(factory, ScaffoldApp.isMobile() ? BriefAnswerMobileEditView.instance() : BriefAnswerDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<BriefAnswerProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<BriefAnswerProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        BriefAnswerDesktopEditView.instance().setCreating(false);
        EntityProxyId<BriefAnswerProxy> proxyId = coerceId(place);
        Activity activity = new BriefAnswerEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? BriefAnswerMobileEditView.instance() : BriefAnswerDesktopEditView.instance(), placeController);
        return new BriefAnswerEditActivityWrapper(factory, ScaffoldApp.isMobile() ? BriefAnswerMobileEditView.instance() : BriefAnswerDesktopEditView.instance(), activity, proxyId);
    }
}
