// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.CategoryDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.CategoryDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.CategoryDesktopListView;
import cn.jhc.myexam.client.managed.ui.editor.CategoryListEditor;
import cn.jhc.myexam.client.managed.ui.editor.UserSetEditor;
import cn.jhc.myexam.client.managed.ui.mobile.CategoryMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.CategoryMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.request.CategoryRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import java.util.List;
import java.util.Set;

public abstract class CategoryActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        CategoryDesktopEditView.instance().setCreating(true);
        Activity activity = new CategoryEditActivity(null, factory, ScaffoldApp.isMobile() ? CategoryMobileEditView.instance() : CategoryDesktopEditView.instance(), placeController);
        return new CategoryEditActivityWrapper(factory, ScaffoldApp.isMobile() ? CategoryMobileEditView.instance() : CategoryDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<CategoryProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<CategoryProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        CategoryDesktopEditView.instance().setCreating(false);
        EntityProxyId<CategoryProxy> proxyId = coerceId(place);
        Activity activity = new CategoryEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? CategoryMobileEditView.instance() : CategoryDesktopEditView.instance(), placeController);
        return new CategoryEditActivityWrapper(factory, ScaffoldApp.isMobile() ? CategoryMobileEditView.instance() : CategoryDesktopEditView.instance(), activity, proxyId);
    }
}
