// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.FillBlankDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.FillBlankDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.FillBlankDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.FillBlankMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.FillBlankMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.FillBlankProxy;
import cn.jhc.myexam.client.request.FillBlankRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class FillBlankActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        FillBlankDesktopEditView.instance().setCreating(true);
        Activity activity = new FillBlankEditActivity(null, factory, ScaffoldApp.isMobile() ? FillBlankMobileEditView.instance() : FillBlankDesktopEditView.instance(), placeController);
        return new FillBlankEditActivityWrapper(factory, ScaffoldApp.isMobile() ? FillBlankMobileEditView.instance() : FillBlankDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<FillBlankProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<FillBlankProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        FillBlankDesktopEditView.instance().setCreating(false);
        EntityProxyId<FillBlankProxy> proxyId = coerceId(place);
        Activity activity = new FillBlankEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? FillBlankMobileEditView.instance() : FillBlankDesktopEditView.instance(), placeController);
        return new FillBlankEditActivityWrapper(factory, ScaffoldApp.isMobile() ? FillBlankMobileEditView.instance() : FillBlankDesktopEditView.instance(), activity, proxyId);
    }
}
