// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.GlossaryDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.GlossaryDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.GlossaryDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.GlossaryMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.GlossaryMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.GlossaryProxy;
import cn.jhc.myexam.client.request.GlossaryRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class GlossaryActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        GlossaryDesktopEditView.instance().setCreating(true);
        Activity activity = new GlossaryEditActivity(null, factory, ScaffoldApp.isMobile() ? GlossaryMobileEditView.instance() : GlossaryDesktopEditView.instance(), placeController);
        return new GlossaryEditActivityWrapper(factory, ScaffoldApp.isMobile() ? GlossaryMobileEditView.instance() : GlossaryDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<GlossaryProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<GlossaryProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        GlossaryDesktopEditView.instance().setCreating(false);
        EntityProxyId<GlossaryProxy> proxyId = coerceId(place);
        Activity activity = new GlossaryEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? GlossaryMobileEditView.instance() : GlossaryDesktopEditView.instance(), placeController);
        return new GlossaryEditActivityWrapper(factory, ScaffoldApp.isMobile() ? GlossaryMobileEditView.instance() : GlossaryDesktopEditView.instance(), activity, proxyId);
    }
}
