// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.QuizDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.QuizDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.QuizDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.QuizMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.QuizMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.QuizProxy;
import cn.jhc.myexam.client.request.QuizRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class QuizActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        QuizDesktopEditView.instance().setCreating(true);
        Activity activity = new QuizEditActivity(null, factory, ScaffoldApp.isMobile() ? QuizMobileEditView.instance() : QuizDesktopEditView.instance(), placeController);
        return new QuizEditActivityWrapper(factory, ScaffoldApp.isMobile() ? QuizMobileEditView.instance() : QuizDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<QuizProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<QuizProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        QuizDesktopEditView.instance().setCreating(false);
        EntityProxyId<QuizProxy> proxyId = coerceId(place);
        Activity activity = new QuizEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? QuizMobileEditView.instance() : QuizDesktopEditView.instance(), placeController);
        return new QuizEditActivityWrapper(factory, ScaffoldApp.isMobile() ? QuizMobileEditView.instance() : QuizDesktopEditView.instance(), activity, proxyId);
    }
}
