// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.RoleDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.RoleDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.RoleDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.RoleMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.RoleMobileEditView;
import cn.jhc.myexam.client.proxy.RoleProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.request.RoleRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class RoleActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        RoleDesktopEditView.instance().setCreating(true);
        Activity activity = new RoleEditActivity(null, factory, ScaffoldApp.isMobile() ? RoleMobileEditView.instance() : RoleDesktopEditView.instance(), placeController);
        return new RoleEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RoleMobileEditView.instance() : RoleDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<RoleProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<RoleProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        RoleDesktopEditView.instance().setCreating(false);
        EntityProxyId<RoleProxy> proxyId = coerceId(place);
        Activity activity = new RoleEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? RoleMobileEditView.instance() : RoleDesktopEditView.instance(), placeController);
        return new RoleEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RoleMobileEditView.instance() : RoleDesktopEditView.instance(), activity, proxyId);
    }
}
