// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.SingleChoiceDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.SingleChoiceDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.SingleChoiceDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.SingleChoiceMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.SingleChoiceMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.SingleChoiceProxy;
import cn.jhc.myexam.client.request.SingleChoiceRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class SingleChoiceActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        SingleChoiceDesktopEditView.instance().setCreating(true);
        Activity activity = new SingleChoiceEditActivity(null, factory, ScaffoldApp.isMobile() ? SingleChoiceMobileEditView.instance() : SingleChoiceDesktopEditView.instance(), placeController);
        return new SingleChoiceEditActivityWrapper(factory, ScaffoldApp.isMobile() ? SingleChoiceMobileEditView.instance() : SingleChoiceDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<SingleChoiceProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<SingleChoiceProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        SingleChoiceDesktopEditView.instance().setCreating(false);
        EntityProxyId<SingleChoiceProxy> proxyId = coerceId(place);
        Activity activity = new SingleChoiceEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? SingleChoiceMobileEditView.instance() : SingleChoiceDesktopEditView.instance(), placeController);
        return new SingleChoiceEditActivityWrapper(factory, ScaffoldApp.isMobile() ? SingleChoiceMobileEditView.instance() : SingleChoiceDesktopEditView.instance(), activity, proxyId);
    }
}
