// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.TrueOrFalseDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.TrueOrFalseDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.TrueOrFalseDesktopListView;
import cn.jhc.myexam.client.managed.ui.mobile.TrueOrFalseMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.TrueOrFalseMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.TrueOrFalseProxy;
import cn.jhc.myexam.client.request.TrueOrFalseRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class TrueOrFalseActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        TrueOrFalseDesktopEditView.instance().setCreating(true);
        Activity activity = new TrueOrFalseEditActivity(null, factory, ScaffoldApp.isMobile() ? TrueOrFalseMobileEditView.instance() : TrueOrFalseDesktopEditView.instance(), placeController);
        return new TrueOrFalseEditActivityWrapper(factory, ScaffoldApp.isMobile() ? TrueOrFalseMobileEditView.instance() : TrueOrFalseDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<TrueOrFalseProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<TrueOrFalseProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        TrueOrFalseDesktopEditView.instance().setCreating(false);
        EntityProxyId<TrueOrFalseProxy> proxyId = coerceId(place);
        Activity activity = new TrueOrFalseEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? TrueOrFalseMobileEditView.instance() : TrueOrFalseDesktopEditView.instance(), placeController);
        return new TrueOrFalseEditActivityWrapper(factory, ScaffoldApp.isMobile() ? TrueOrFalseMobileEditView.instance() : TrueOrFalseDesktopEditView.instance(), activity, proxyId);
    }
}
