// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.activity;
import cn.jhc.myexam.client.managed.request.ApplicationRequestFactory;
import cn.jhc.myexam.client.managed.ui.desktop.UserDesktopDetailsView;
import cn.jhc.myexam.client.managed.ui.desktop.UserDesktopEditView;
import cn.jhc.myexam.client.managed.ui.desktop.UserDesktopListView;
import cn.jhc.myexam.client.managed.ui.editor.CategorySetEditor;
import cn.jhc.myexam.client.managed.ui.editor.RoleListEditor;
import cn.jhc.myexam.client.managed.ui.mobile.UserMobileDetailsView;
import cn.jhc.myexam.client.managed.ui.mobile.UserMobileEditView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.RoleProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.request.UserRequest;
import cn.jhc.myexam.client.scaffold.ScaffoldApp;
import cn.jhc.myexam.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import java.util.List;
import java.util.Set;

public abstract class UserActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        UserDesktopEditView.instance().setCreating(true);
        Activity activity = new UserEditActivity(null, factory, ScaffoldApp.isMobile() ? UserMobileEditView.instance() : UserDesktopEditView.instance(), placeController);
        return new UserEditActivityWrapper(factory, ScaffoldApp.isMobile() ? UserMobileEditView.instance() : UserDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<UserProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<UserProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        UserDesktopEditView.instance().setCreating(false);
        EntityProxyId<UserProxy> proxyId = coerceId(place);
        Activity activity = new UserEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? UserMobileEditView.instance() : UserDesktopEditView.instance(), placeController);
        return new UserEditActivityWrapper(factory, ScaffoldApp.isMobile() ? UserMobileEditView.instance() : UserDesktopEditView.instance(), activity, proxyId);
    }
}
