// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.ui.desktop;
import cn.jhc.myexam.client.proxy.BriefAnswerProxy;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.scaffold.place.AbstractProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;

public abstract class BriefAnswerDesktopListView_Roo_Gwt extends AbstractProxyListView<BriefAnswerProxy> {

    @UiField
    CellTable<BriefAnswerProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<BriefAnswerProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(BriefAnswerProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("question");
        table.addColumn(new TextColumn<BriefAnswerProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(BriefAnswerProxy object) {
                return renderer.render(object.getQuestion());
            }
        }, "Question");
        paths.add("answer");
        table.addColumn(new TextColumn<BriefAnswerProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(BriefAnswerProxy object) {
                return renderer.render(object.getAnswer());
            }
        }, "Answer");
        paths.add("category");
        table.addColumn(new TextColumn<BriefAnswerProxy>() {

            Renderer<cn.jhc.myexam.client.proxy.CategoryProxy> renderer = cn.jhc.myexam.client.managed.ui.renderer.CategoryProxyRenderer.instance();

            @Override
            public String getValue(BriefAnswerProxy object) {
                return renderer.render(object.getCategory());
            }
        }, "Category");
        paths.add("version");
        table.addColumn(new TextColumn<BriefAnswerProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(BriefAnswerProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
