// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.ui.desktop;
import cn.jhc.myexam.client.managed.ui.editor.CategoryListEditor;
import cn.jhc.myexam.client.managed.ui.editor.UserSetEditor;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.scaffold.place.AbstractProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public abstract class CategoryDesktopListView_Roo_Gwt extends AbstractProxyListView<CategoryProxy> {

    @UiField
    CellTable<CategoryProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("name");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getName());
            }
        }, "Name");
        paths.add("info");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getInfo());
            }
        }, "Info");
        paths.add("parent");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<cn.jhc.myexam.client.proxy.CategoryProxy> renderer = cn.jhc.myexam.client.managed.ui.renderer.CategoryProxyRenderer.instance();

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getParent());
            }
        }, "Parent");
        paths.add("children");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<java.util.List> renderer = cn.jhc.myexam.client.scaffold.place.CollectionRenderer.of(cn.jhc.myexam.client.managed.ui.renderer.CategoryProxyRenderer.instance());

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getChildren());
            }
        }, "Children");
        paths.add("users");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<java.util.Set> renderer = cn.jhc.myexam.client.scaffold.place.CollectionRenderer.of(cn.jhc.myexam.client.managed.ui.renderer.UserProxyRenderer.instance());

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getUsers());
            }
        }, "Users");
        paths.add("version");
        table.addColumn(new TextColumn<CategoryProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CategoryProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
