// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.ui.desktop;
import cn.jhc.myexam.client.managed.ui.FillBlankDetailsView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.FillBlankProxy;
import cn.jhc.myexam.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class FillBlankDesktopDetailsView_Roo_Gwt extends Composite implements FillBlankDetailsView {

    @UiField
    SpanElement id;

    @UiField
    SpanElement question;

    @UiField
    SpanElement quantity;

    @UiField
    SpanElement answer;

    @UiField
    SpanElement category;

    @UiField
    SpanElement version;

    FillBlankProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(FillBlankProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        question.setInnerText(proxy.getQuestion() == null ? "" : String.valueOf(proxy.getQuestion()));
        quantity.setInnerText(proxy.getQuantity() == null ? "" : String.valueOf(proxy.getQuantity()));
        answer.setInnerText(proxy.getAnswer() == null ? "" : String.valueOf(proxy.getAnswer()));
        category.setInnerText(proxy.getCategory() == null ? "" : cn.jhc.myexam.client.managed.ui.renderer.CategoryProxyRenderer.instance().render(proxy.getCategory()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(cn.jhc.myexam.client.managed.ui.renderer.FillBlankProxyRenderer.instance().render(proxy));
    }
}
