// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.ui.desktop;
import cn.jhc.myexam.client.managed.ui.QuizDetailsView;
import cn.jhc.myexam.client.proxy.CategoryProxy;
import cn.jhc.myexam.client.proxy.QuizProxy;
import cn.jhc.myexam.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class QuizDesktopDetailsView_Roo_Gwt extends Composite implements QuizDetailsView {

    @UiField
    SpanElement id;

    @UiField
    SpanElement name;

    @UiField
    SpanElement info;

    @UiField
    SpanElement timeOpen;

    @UiField
    SpanElement timeClose;

    @UiField
    SpanElement content;

    @UiField
    SpanElement category;

    @UiField
    SpanElement version;

    QuizProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(QuizProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        info.setInnerText(proxy.getInfo() == null ? "" : String.valueOf(proxy.getInfo()));
        timeOpen.setInnerText(proxy.getTimeOpen() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getTimeOpen()));
        timeClose.setInnerText(proxy.getTimeClose() == null ? "" : DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.DATE_SHORT).format(proxy.getTimeClose()));
        content.setInnerText(proxy.getContent() == null ? "" : String.valueOf(proxy.getContent()));
        category.setInnerText(proxy.getCategory() == null ? "" : cn.jhc.myexam.client.managed.ui.renderer.CategoryProxyRenderer.instance().render(proxy.getCategory()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(cn.jhc.myexam.client.managed.ui.renderer.QuizProxyRenderer.instance().render(proxy));
    }
}
