// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package cn.jhc.myexam.client.managed.ui.desktop;
import cn.jhc.myexam.client.managed.ui.RoleDetailsView;
import cn.jhc.myexam.client.proxy.RoleProxy;
import cn.jhc.myexam.client.proxy.UserProxy;
import cn.jhc.myexam.client.scaffold.place.ProxyListView;
import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;

public abstract class RoleDesktopDetailsView_Roo_Gwt extends Composite implements RoleDetailsView {

    @UiField
    SpanElement id;

    @UiField
    SpanElement rolename;

    @UiField
    SpanElement user;

    @UiField
    SpanElement version;

    RoleProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(RoleProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        rolename.setInnerText(proxy.getRolename() == null ? "" : String.valueOf(proxy.getRolename()));
        user.setInnerText(proxy.getUser() == null ? "" : cn.jhc.myexam.client.managed.ui.renderer.UserProxyRenderer.instance().render(proxy.getUser()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        displayRenderer.setInnerText(cn.jhc.myexam.client.managed.ui.renderer.RoleProxyRenderer.instance().render(proxy));
    }
}
