package cn.jhc.myexam.vaadin.view;

import org.apache.bcel.generic.NEW;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import cn.jhc.myexam.server.domain.User;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("prototype")
public class AddUserView extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	
	private final static String[] userPropertyNames = new String[]{
		"username", "password", "enabled", "displayName"
	};

	private FormLayout formLayout;

	private static final long serialVersionUID = 1L;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AddUserView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		buildFormLayout();
	}

	private void buildFormLayout() {
		formLayout = new FormLayout();
		mainLayout.addComponent(formLayout);
		mainLayout.setComponentAlignment(formLayout, Alignment.MIDDLE_CENTER);
		
		formLayout.setMargin(true);
		FieldGroup userFieldGroup = new BeanFieldGroup<User>(User.class);
		userFieldGroup.setItemDataSource(new BeanItem<User>(new User()));
		for(String p : userPropertyNames){
			formLayout.addComponent(userFieldGroup.buildAndBind(p));
		}
	}

	@Override
	public void enter(ViewChangeEvent event) {
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		return mainLayout;
	}

}
