package cn.jhc.myexam.vaadin.view;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

@Component @Scope("prototype")
public class DashboardView extends CustomComponent implements View{

	private VerticalLayout mainLayout;

	private Label mainLabel;
	/**
	 * The constructor should first build the MAIN layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DashboardView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@Override
	public void enter(ViewChangeEvent event) {
	}

	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// mainLabel
		mainLabel = new Label();
		mainLabel.setImmediate(false);
		mainLabel.setWidth("100.0%");
		mainLabel.setHeight("-1px");
		mainLabel.setValue("服务器状态信息：");
		mainLayout.addComponent(mainLabel);
		
		return mainLayout;
	}

}
