package cn.jhc.myexam.vaadin.view;

import java.util.Arrays;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import cn.jhc.myexam.shared.domain.QuestionType;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@Component @Scope("prototype") @SuppressWarnings("serial")
public class QuestionsManagerView extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table questionsTable;
	@AutoGenerated
	private HorizontalLayout selectQuestionsTypeLayout;
	@AutoGenerated
	private ComboBox questionTypesComboBox;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public QuestionsManagerView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// selectQuestionsTypeLayout
		selectQuestionsTypeLayout = buildSelectQuestionsTypeLayout();
		mainLayout.addComponent(selectQuestionsTypeLayout);
		
		// questionsTable
		questionsTable = new Table();
		questionsTable.setImmediate(false);
		questionsTable.setWidth("100.0%");
		questionsTable.setHeight("-1px");
		mainLayout.addComponent(questionsTable);
		
		return mainLayout;
	}

	private HorizontalLayout buildSelectQuestionsTypeLayout() {
		// common part: create layout
		selectQuestionsTypeLayout = new HorizontalLayout();
		selectQuestionsTypeLayout.setImmediate(false);
		selectQuestionsTypeLayout.setWidth("100.0%");
		selectQuestionsTypeLayout.setHeight("-1px");
		selectQuestionsTypeLayout.setMargin(true);
		
		// questionTypesComboBox
		questionTypesComboBox = new ComboBox("选择题型", Arrays.asList(QuestionType.values()));
		questionTypesComboBox.setImmediate(false);
		questionTypesComboBox.setWidth("-1px");
		questionTypesComboBox.setHeight("-1px");
		selectQuestionsTypeLayout.addComponent(questionTypesComboBox);
		
		return selectQuestionsTypeLayout;
	}

	@Override
	public void enter(ViewChangeEvent event) {
	}

}
