package cn.jhc.myexam.vaadin.view;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import cn.jhc.myexam.server.service.QuestionsService;
import cn.jhc.myexam.shared.domain.QuestionType;
import cn.jhc.myexam.vaadin.builder.VaadinEntityBuilder;
import cn.jhc.myexam.vaadin.factory.QuestionTypeFactory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbstractSelect.ItemCaptionMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@Component @Scope("prototype") @SuppressWarnings("serial")
public class QuestionsManagerView extends CustomComponent implements View, ValueChangeListener{

	private QuestionsService questionsService;
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table questionsTable;
	@AutoGenerated
	private HorizontalLayout selectQuestionsTypeLayout;
	@AutoGenerated
	private ComboBox questionTypesComboBox;

	private HorizontalLayout horizontalButtonsLayout;

	private NativeButton addQuestionButton;

	private NativeButton importQuestionsButton;
	/**
	 * The constructor should first build the MAIN layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	@Autowired
	public QuestionsManagerView(QuestionsService questionsService) {
		this.questionsService = questionsService;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		questionTypesComboBox.addValueChangeListener(this);
//		questionTypesComboBox.setValue(QuestionType.SINGLE_CHOICE);
		addQuestionButton.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				
			}
		});
	}

	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// selectQuestionsTypeLayout
		buildSelectQuestionsTypeLayout();
		mainLayout.addComponent(selectQuestionsTypeLayout);
		
		// questionsTable
		questionsTable = new Table();
		questionsTable.setImmediate(true);
		questionsTable.setWidth("100.0%");
		questionsTable.setHeight("-1px");
		mainLayout.addComponent(questionsTable);
		
		buildHorizontalLayout();
		mainLayout.addComponent(horizontalButtonsLayout);
		
		return mainLayout;
	}

	private HorizontalLayout buildSelectQuestionsTypeLayout() {
		// common part: create layout
		selectQuestionsTypeLayout = new HorizontalLayout();
		selectQuestionsTypeLayout.setImmediate(false);
		selectQuestionsTypeLayout.setWidth("100.0%");
		selectQuestionsTypeLayout.setHeight("-1px");
		selectQuestionsTypeLayout.setMargin(true);
		
		// questionTypesComboBox
		final Container questionTypeContainer = QuestionTypeFactory.getQuestionTypeContainer();
		questionTypesComboBox = new ComboBox("选择题型", questionTypeContainer);
		questionTypesComboBox.setItemCaptionMode(ItemCaptionMode.PROPERTY);
		questionTypesComboBox.setItemCaptionPropertyId("description");
		questionTypesComboBox.setImmediate(true);
		questionTypesComboBox.setWidth("-1px");
		questionTypesComboBox.setHeight("-1px");
		selectQuestionsTypeLayout.addComponent(questionTypesComboBox);

		return selectQuestionsTypeLayout;
	}

	private HorizontalLayout buildHorizontalLayout() {
		// common part: create layout
		horizontalButtonsLayout = new HorizontalLayout();
		horizontalButtonsLayout.setImmediate(false);
		horizontalButtonsLayout.setWidth("-1px");
		horizontalButtonsLayout.setHeight("40px");
		horizontalButtonsLayout.setMargin(false);
		horizontalButtonsLayout.setSpacing(true);
		
		// addQuestionButton
		addQuestionButton = new NativeButton();
		addQuestionButton.setStyleName("page-button");
		addQuestionButton.setCaption("添加题目");
		addQuestionButton.setImmediate(true);
		addQuestionButton.setDescription("点击这里可以添加单个题目");
		addQuestionButton.setWidth("-1px");
		addQuestionButton.setHeight("100.0%");
		horizontalButtonsLayout.addComponent(addQuestionButton);
		horizontalButtonsLayout
				.setComponentAlignment(addQuestionButton, new Alignment(48));
		
		// importQuestionsButton
		importQuestionsButton = new NativeButton();
		importQuestionsButton.setStyleName("page-button");
		importQuestionsButton.setCaption("从Excel导入多个题目");
		importQuestionsButton.setImmediate(true);
		importQuestionsButton.setDescription("点击这里可以从Excel中导入多个题目");
		importQuestionsButton.setWidth("-1px");
		importQuestionsButton.setHeight("100.0%");
		horizontalButtonsLayout.addComponent(importQuestionsButton);
		horizontalButtonsLayout.setComponentAlignment(importQuestionsButton,
				new Alignment(48));
		
		return horizontalButtonsLayout;
	}
	@Override
	public void enter(ViewChangeEvent event) {
	}

	@SuppressWarnings("rawtypes")
	@Override
	public void valueChange(ValueChangeEvent event) {
		QuestionType type = (QuestionType)event.getProperty().getValue();
		List list = questionsService.findAllQuestion(type);
		Class<?> theClass = type.getEntityClass();
		BeanItemContainer<?> container = new BeanItemContainer(theClass);
		container.addAll(list);
		VaadinEntityBuilder.create(theClass).modifyTable(questionsTable, container);
	}

}
